spring:
  output:
    ansi:
      enabled: always # ?? ?? ??
  thymeleaf:
    cache: false # ???? ?? ??
    prefix: classpath:/templates/ #
    suffix: .html
  application:
    name: basic1
  datasource:
    # ?????? ?? URL
    url: jdbc:mariadb://localhost:3306/basic1__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    #url: jdbc:mysql://localhost:3306/basic1__dev?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: demo
    password: demo
    driver-class-name: org.mariadb.jdbc.Driver
    #com.mysql.cj.jdbc.Driver

  # server:
  # port: 8080


  jpa:
    hibernate:
      ddl-auto: update  # create, create-drop, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

server:
  servlet:
    context-path: /