spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
    prefix: classpath:/templates/ #
    suffix: .html
  application:
    name: basic1
  datasource:
    #url: jdbc:mariadb://localhost:3306/basic1__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    #url: jdbc:mysql://localhost:3306/basic1__dev?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    url: jdbc:postgresql://localhost:5432/test_db
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver
    #com.mysql.cj.jdbc.Driver


  # server:
  # port: 8080

  jpa:
    hibernate:
      ddl-auto: update  # create, create-drop, update, validate, none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        #highlight_sql: true
p6spy:
  config:
    sqlformat: true
    # JDBC 이벤트 로깅을 위한 P6LogFactory 등록
    enable-logging: true
    # com.p6spy.engine.spy.appender.MultiLineFormat 사용 (SingleLineFormat 대신)
    multiline: true
    # 기본 리스너들을 위한 로깅 사용 [slf4j, sysout, file, custom]
    logging: slf4j
    # 실제 값으로 '?'를 대체한 효과적인 SQL 문자열을 추적 시스템에 보고
    # 참고: 이 설정은 로깅 메시지에 영향을 주지 않음
    tracing:
      include-parameter-values: true

#server:
#  servlet:
#    context-path: /

